---
- name: set up motd file
  hosts: all
  tasks:
  - name: configure motd
    template:
      src: motd.j2
      dest: /etc/motd
  - name: add line for sdb if it does not exist
    lineinfile:
      path: /etc/motd
      line: 'Secondary disk size: NOT AVAILABLE'
    when: ansible_devices.sdb is not defined
  - name: add line for sdb if it exists
    lineinfile:
      path: /etc/motd
      line: "Secondary disk size: {{ ansible_facts['devices']['sdb']['size'] }}"
    when: ansible_devices.sdb is defined
