---
- name: create LVM logical volumes
  hosts: all
  tasks:
  - name: create logical volumes
    lvol:
      vg: vgdata
      lv: lvdata
      size: "2000m"
    ignore_errors: yes
    register: result
# in the assignment he says to cretae a custom error message but I think that's stupid as the default message already gives that info.
