---
- name: create LVM logical volumes
  hosts: all
  tasks:
  - name: create logical volumes
    lvol:
      vg: vgdata
      lv: lvdata
      size: "2000m"
    when: ansible_lvm.vgs.vgdata is defined and ansible_lvm.vgs.vgdata.size_g >= "2.00"
  - fail:
      msg: vgdata does not exist
    when: ansible_lvm.vgs.vgdata is not defined
  - fail:
      msg: insufficient size
    when: ansible_lvm.vgs.vgdata.size_g <= "2.00"
